import {
  CalendarDays,
  Camera,
  CloudSun,
  Clock3,
  Compass,
  Folder,
  Gamepad2,
  Grid3X3,
  Images,
  MessageCircle,
  Music2,
  NotebookText,
  Phone,
  Settings,
  Store,
} from "lucide-react";

import type { AppDefinition } from "./types";

export const appRegistry: AppDefinition[] = [
  {
    id: "finder",
    name: "Finder",
    category: "system",
    icon: Folder,
    iconSrc: "/app-icons/finder.svg",
    accent: "#3b82f6",
    defaultSize: { width: 920, height: 620 },
    minSize: { width: 680, height: 460 },
    dock: true,
    desktop: true,
    menuItems: ["File", "Edit", "View", "Go", "Window", "Help"],
  },
  {
    id: "notes",
    name: "Notes",
    category: "personal",
    icon: NotebookText,
    iconSrc: "/app-icons/notes.svg",
    accent: "#f4c430",
    defaultSize: { width: 960, height: 640 },
    minSize: { width: 720, height: 500 },
    dock: true,
    desktop: true,
    menuItems: ["File", "Edit", "Format", "View", "Window", "Help"],
  },
  {
    id: "photos",
    name: "Gallery",
    category: "personal",
    icon: Images,
    iconSrc: "/app-icons/photos.svg",
    accent: "#ef4444",
    defaultSize: { width: 1040, height: 680 },
    minSize: { width: 760, height: 520 },
    dock: true,
    desktop: true,
    menuItems: ["File", "Edit", "Image", "View", "Window", "Help"],
  },
  {
    id: "camera",
    name: "Camera",
    category: "utility",
    icon: Camera,
    iconSrc: "/app-icons/photo-booth.svg",
    accent: "#ef4444",
    defaultSize: { width: 760, height: 580 },
    minSize: { width: 620, height: 500 },
    dock: true,
    desktop: false,
    menuItems: ["File", "Edit", "Camera", "Window", "Help"],
  },
  {
    id: "spotify",
    name: "Jukebox",
    category: "media",
    icon: Music2,
    iconSrc: "/app-icons/spotify.svg",
    accent: "#1db954",
    defaultSize: { width: 1050, height: 680 },
    minSize: { width: 780, height: 540 },
    dock: true,
    desktop: true,
    menuItems: ["Jukebox", "File", "Edit", "Playback", "View", "Help"],
  },
  {
    id: "whatsapp",
    name: "Chat",
    category: "media",
    icon: MessageCircle,
    iconSrc: "/app-icons/whatsapp.svg",
    accent: "#25d366",
    defaultSize: { width: 1000, height: 660 },
    minSize: { width: 760, height: 520 },
    dock: true,
    desktop: true,
    menuItems: ["Chat", "Edit", "View", "Conversation", "Window", "Help"],
  },
  {
    id: "phone",
    name: "Calls",
    category: "personal",
    icon: Phone,
    iconSrc: "/app-icons/calls.svg",
    accent: "#22c55e",
    defaultSize: { width: 760, height: 560 },
    minSize: { width: 620, height: 460 },
    dock: false,
    desktop: true,
    menuItems: ["File", "Edit", "View", "Call", "Window", "Help"],
  },
  {
    id: "weather",
    name: "Weather",
    category: "utility",
    icon: CloudSun,
    iconSrc: "/app-icons/weather.svg",
    accent: "#38bdf8",
    defaultSize: { width: 780, height: 620 },
    minSize: { width: 620, height: 480 },
    dock: true,
    desktop: false,
    menuItems: ["File", "View", "Window", "Help"],
  },
  {
    id: "clock",
    name: "Clock",
    category: "utility",
    icon: Clock3,
    iconSrc: "/app-icons/clock.svg",
    accent: "#f97316",
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 640, height: 460 },
    dock: false,
    desktop: true,
    menuItems: ["File", "Edit", "View", "Window", "Help"],
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "personal",
    icon: CalendarDays,
    iconSrc: "/app-icons/calendar.svg",
    accent: "#ef4444",
    defaultSize: { width: 960, height: 640 },
    minSize: { width: 720, height: 520 },
    dock: true,
    desktop: true,
    menuItems: ["File", "Edit", "View", "Window", "Help"],
  },
  {
    id: "settings",
    name: "System Settings",
    category: "system",
    icon: Settings,
    iconSrc: "/app-icons/system-settings.svg",
    accent: "#94a3b8",
    defaultSize: { width: 900, height: 620 },
    minSize: { width: 720, height: 520 },
    dock: true,
    desktop: false,
    menuItems: ["File", "Edit", "View", "Window", "Help"],
  },
  {
    id: "app-store",
    name: "App Store",
    category: "system",
    icon: Store,
    iconSrc: "/app-icons/app-store.svg",
    accent: "#0ea5e9",
    defaultSize: { width: 920, height: 620 },
    minSize: { width: 720, height: 500 },
    dock: false,
    desktop: true,
    menuItems: ["Store", "Edit", "View", "Window", "Help"],
  },
  {
    id: "zip",
    name: "Zip",
    category: "game",
    icon: Gamepad2,
    iconSrc: "/app-icons/zip.svg",
    accent: "#a855f7",
    defaultSize: { width: 880, height: 660 },
    minSize: { width: 720, height: 540 },
    dock: false,
    desktop: true,
    menuItems: ["Game", "Edit", "View", "Window", "Help"],
  },
  {
    id: "arrow",
    name: "Arrow Escape",
    category: "game",
    icon: Compass,
    iconSrc: "/app-icons/arrow-escape.svg",
    accent: "#f59e0b",
    defaultSize: { width: 880, height: 660 },
    minSize: { width: 720, height: 540 },
    dock: false,
    desktop: true,
    menuItems: ["Game", "Edit", "View", "Window", "Help"],
  },
  {
    id: "wordle",
    name: "Wordle",
    category: "game",
    icon: Grid3X3,
    accent: "#22c55e",
    defaultSize: { width: 880, height: 660 },
    minSize: { width: 720, height: 540 },
    dock: false,
    desktop: true,
    menuItems: ["Game", "Edit", "View", "Window", "Help"],
  },
];

export const dockApps = appRegistry.filter((app) => app.dock);
export const desktopApps = appRegistry.filter((app) => app.desktop);

export function getAppDefinition(appId: string) {
  return appRegistry.find((app) => app.id === appId);
}
